site_name: Docs as Code

theme:
  name: readthedocs

plugins:
  - search
  - mermaid2

nav:
  - Главная: index.md
  - Проект ACMS Censor:
      - Описание: project/overview.md
      - Требования: project/requirements.md
      - Диаграммы: project/diagrams.md
